🐛 fix(script): add utils/docs to PYTHONPATH for llvm_sphinx import (GH-58)
Since llvm/llvm-project@42ff45b introduced the llvm_sphinx module under
utils/docs/, add it to PYTHONPATH so Sphinx can import it. Fixes:

    ModuleNotFoundError: No module named 'llvm_sphinx'

Synced from: localizethedocs/llvm-docs-l10n@c4093fc